### PR TITLE
Add firefox extension types

### PR DESCRIPTION
**Pull request by janat08**

### CODE REVIEW

**Comment by samrum** [comment]
What are these types for?

**Comment by janat08** [comment]
URL input events.

**Comment by samrum** [comment]
But why are they being added here? Nothing in this plugin would be using it so it seems like a project specific dependency.

**Comment by janat08** [comment]
I must've believed this was a scaffolding tool or a starter template.

**Comment by samrum** [comment]
The create/scaffolding related project of the plugin is in https://github.com/samrum/create-vite-plugin-web-extension

But the expectation with those is that you'd be using `webextension-polyfill` to access browser APIs and get type definitions via `@types/webextension-polyfill`. If there were issues with `@types/webextension-polyfill`, I'd probably be more inclined to use one of the alternatives suggested by the library itself, though: https://github.com/mozilla/webextension-polyfill#usage-with-typescript

**Pull request closed without merging**
