### PR TITLE
remove incorrect rollup types and bump vite

### LINKED ISSUE #82: rollup types conflict with vite types
```
> tsc
node_modules/@samrum/vite-plugin-web-extension/types/index.d.ts:40:5 - error TS2687: All declarations of 'viteMetadata' must have identical modifiers.

40     viteMetadata: ChunkMetadata;
       ~~~~~~~~~~~~

node_modules/@samrum/vite-plugin-web-extension/types/index.d.ts:40:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'viteMetadata' must be of type 'ChunkMetadata | undefined', but here has type 'ChunkMetadata'.

40     viteMetadata: ChunkMetadata;
       ~~~~~~~~~~~~

  node_modules/vite/types/metadata.d.ts:8:5
    8     viteMetadata?: ChunkMetadata
          ~~~~~~~~~~~~
    'viteMetadata' was also declared here.

node_modules/vite/types/metadata.d.ts:8:5 - error TS2687: All declarations of 'viteMetadata' must have identical modifiers.

8     viteMetadata?: ChunkMetadata
      ~~~~~~~~~~~~


Found 3 errors in 2 files.
```

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #82 

also bump vite to fix another type error, seems to be the same issue as https://github.com/Subwaytime/vite-aliases/issues/36

### CODE REVIEW

**Comment by samrum** [comment]
This is missing the associated changes to pnpm-lock.yaml for the Vite version change.

But, if the intention is to fix downstream usages of the plugin, you might want to update the Vite version in https://github.com/samrum/create-vite-plugin-web-extension instead.

If the intention is to fix type issues in the plugin itself, you'd need to commit the updated pnpm-lock-yaml here.

**Comment by DetachHead** [comment]
> This is missing the associated changes to pnpm-lock.yaml for the Vite version change.

sorry about that, pnpm doesn't work on my work PC. i've updated it now

**Comment by DetachHead** [comment]
no idea why but the errors in the CI are different to the errors i get locally:

### ci
```
 > tsc --noEmit && rollup -c

src/manifestParser/manifestParser.ts:304:15 - error TS2339: Property 'viteMetadata' does not exist on type 'OutputChunk'.

304     chunkInfo.viteMetadata.importedCss.forEach(metadata.css.add, metadata.css);
                  ~~~~~~~~~~~~

src/manifestParser/manifestParser.ts:305:15 - error TS2339: Property 'viteMetadata' does not exist on type 'OutputChunk'.

305     chunkInfo.viteMetadata.importedAssets.forEach(
                  ~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/manifestParser/manifestParser.ts:304
```

### local
```
> tsc --noEmit && rollup -c

src/manifestParser/manifestParser.ts:304:5 - error TS18048: 'chunkInfo.viteMetadata' is possibly 'undefined'.

304     chunkInfo.viteMetadata.importedCss.forEach(metadata.css.add, metadata.css);
        ~~~~~~~~~~~~~~~~~~~~~~

src/manifestParser/manifestParser.ts:305:5 - error TS18048: 'chunkInfo.viteMetadata' is possibly 'undefined'.

305     chunkInfo.viteMetadata.importedAssets.forEach(
        ~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/manifestParser/manifestParser.ts:304
```

i fixed it in f57d89147ac84e639a5ed3fdb480835733f4ead2 but i think something else is going on because `tsc` in the ci can't seem to find `node_modules/vite/types/metadata.d.ts` at all

**Comment by DetachHead** [comment]
i think it was an issue with the lockfile should be fixed now

**Pull request merged**
